# Setup
title:        A Neoclassical Nerd
tagline:      Notes on Robotics & Deep Learning
baseurl:      ""
paginate:     1
locale:       "en"
url: liaopeiyuan.github.io

# About/contact
author:
  name:       Peiyuan (Alexander) Liao
  url:        https://github.com/liaopeiyuan 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge

