# Setup
title:        Alexander Liao's Blog
tagline:      Notes on Robotics & Deep Learning
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Peiyuan (Alexander) Liao
  url:        https://github.com/liaopeiyuan 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
