# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Peiyuan (Alexander) Liao
  url:        https://github.com/liaopeiyuan 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
